site_name: Lukea
site_description: "Read (Finnish: lukea)."

theme:
  name: 'material'
  custom_dir: overrides
  favicon: images/favicon.png
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  generator: false
  homepage: https://stefan-hagen.website
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sthagen/lukea
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shage

copyright: Copyright &copy; 2022 Stefan Hagen under the MIT license

repo_name: sthagen/lukea
repo_url: https://github.com/sthagen/lukea
edit_uri: ""

plugins:
  - search

nav:
  - Titlepage: 'title.md'
  - Introduction: 'intro.md'
  - References: 'refs.md'
  - Reading: 'read.md'
  - Glossary: 'gloss.md'

markdown_extensions:

extra_javascript:
