site_name: Lukea
site_description: "Read (Finnish: lukea)."

theme:
  name: 'material'
  custom_dir: overrides
  favicon: images/favicon.png
  icon:
    logo:
      logo
  font:
    text: 'Libre Franklin'
    code: 'Source Code Pro'
  features:
  - toc.integrate
  - navigation.top
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: '#0C2D82'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: '#0C2D82'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  generator: true
  homepage: https://stefan-hagen.website
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sthagen/lukea
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shage

extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2022 Stefan Hagen under the MIT license

repo_name: sthagen/lukea
repo_url: https://github.com/sthagen/lukea
edit_uri: ""

plugins:
  - search

nav:
  - 'Cover Navigation': 'index.md'
  - 'The Wun':
    - Titlepage: 'wun/title.md'
    - Introduction: 'wun/intro.md'
    - References: 'wun/refs.md'
    - Reading: 'wun/read.md'
    - Glossary: 'wun/gloss.md'
  - 'The Two':
    - Titlepage: 'two/title.md'
    - Introduction: 'two/intro.md'
    - References: 'two/refs.md'
    - Writing: 'two/write.md'
    - Glossary: 'two/gloss.md'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: '∞'

extra_javascript:
